development: 
  cloud_name: "blind-barber"
  api_key: "182642887997881"
  api_secret: "aomJ_y3iM3uESccu3EMJLSUY_aQ"
  secure: true

production:
  cloud_name: "blind-barber"
  api_key: "182642887997881"
  api_secret: "aomJ_y3iM3uESccu3EMJLSUY_aQ"
  secure:true